plugins {
    id("idea")
    id("eclipse")
    id("maven-publish")
    id("net.kyori.blossom") version "2.1.0" // https://github.com/KyoriPowered/blossom
    id("dev.ithundxr.silk") version "0.11.15" // https://github.com/ithundxr/silk
    id("me.modmuss50.mod-publish-plugin") version "0.8.4" // https://github.com/modmuss50/mod-publish-plugin
    id("net.neoforged.moddev.legacyforge") version "2.0.107" // https://projects.neoforged.net/neoforged/ModDevGradle
    id("org.jetbrains.gradle.plugin.idea-ext") version "1.1.8" // https://github.com/JetBrains/gradle-idea-ext-plugin
}

apply(from: "./gradle/java.gradle")

boolean dev = System.getenv("RELEASE") == null || System.getenv("RELEASE") == "false"
ext.buildNumber = System.getenv("BUILD_NUMBER")
String gitHash = calculateGitHash() + (hasUnstaged() ? "-modified" : "")

base {
    archivesName = "createnuclear-${artifact_minecraft_version}"
    group = mod_group_id
    version = "${mod_version}-forge" + (dev && buildNumber != null ? "-${buildNumber}" : "")
}

println "Java: ${System.getProperty 'java.version'}, " +
        "JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), " +
        "Arch: ${System.getProperty 'os.arch'}"


Provider<RegularFile> refmap
mixin {
    refmap = add(sourceSets.main, "createnuclear.refmap.json")
    // add sourceSets.main, 'createnuclear.forge.refmap.json'
    config 'createnuclear.forge.mixins.json'
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    accessTransformers {
        from(file("src/main/resources/META-INF/accesstransformer.cfg"))
    }

    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = mapping_version
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }

    // Default run configurations.
    // These can be tweaked, removed, or duplicated as needed.
    runs {
        // applies to all the run configs below
        configureEach {
            systemProperty("forge.logging.markers", "REGISTRIES")
            systemProperty("forge.logging.console.level", "info")
            jvmArguments.addAll("-XX:+IgnoreUnrecognizedVMOptions", "-XX:+AllowEnhancedClassRedefinition")
            //jvmArgument("-XX:-OmitStackTraceInFastThrow") // uncomment when you get exceptions with null messages etc
            //jvmArgument("-XX:+UnlockCommercialFeatures") // uncomment for profiling

            systemProperty("mixin.debug.export", "true")
            systemProperty("mixin.debug.verbose", "true")

            programArgument("-mixin.config=createnuclear.forge.mixins.json")

            systemProperty("mixin.env.remapRefMap", "true")
            systemProperty("mixin.env.refMapRemappingFile", "${projectDir}/build/moddev/artifacts/intermediateToNamed.srg")
        }

        client {
            client()
            gameDirectory = project.file('run')
        }

        client2 {
            client()
            gameDirectory = project.file('run/client2')
            programArguments.addAll('--username', 'Dev2')
        }

        server {
            server()
        }

        // This run config launches GameTestServer and runs all registered gametests, then exits.
        // By default, the server will crash when no gametests are provided.
        // The gametest system is also enabled by default for other run configs under the /test command.
        gameTestServer {
            type = "gameTestServer"
            gameDirectory = project.file('run/gametest')
            systemProperty('forge.enabledGameTestNamespaces', mod_id)
        }

        data {
            data()

            gameDirectory = project.file("run")
            systemProperty("forge.logging.markers", "REGISTRIES,REGISTRYDUMP")
            systemProperty("forge.logging.console.level", "debug")
            programArguments.addAll(
                "--mod", mod_id as String,
                "--all",
                "--output", file("src/generated/resources/").getAbsolutePath(),
                "--existing", file("src/main/resources").getAbsolutePath()
            )
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

repositories {
    maven {
        // location of the maven that hosts JEI files before January 2023
        name = "Progwml6's maven"
        url = "https://dvs1.progwml6.com/files/maven/"
    }
    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    maven {
        url "https://cursemaven.com"
    }

    maven { url = "https://maven.createmod.net" } // Create, Ponder, Flywheel
    maven { url = "https://maven.tterrag.com" } // Registrate
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" } // ForgeConfigAPIPort
}

dependencies {
    /* other minecraft dependencies are here */
    modImplementation("curse.maven:jade-324717:6106101")

    // compile against the JEI API but do not include it at runtime
    modCompileOnly("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    modCompileOnly("mezz.jei:jei-${minecraft_version}-forge-api:${jei_version}")

    // at runtime, use the full JEI jar for Forge

    //Alex's cave
    modCompileOnly("curse.maven:alexs-caves-924854:5848216")
    modCompileOnly("curse.maven:citadel-331936:6002521")

    modImplementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    modImplementation("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}")
    modCompileOnly("dev.engine-room.flywheel:flywheel-forge-api-${minecraft_version}:${flywheel_version}")
    modRuntimeOnly("dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version}")
    modImplementation("com.tterrag.registrate:Registrate:${registrate_version}")

    switch (recipe_viewer.toLowerCase(Locale.ROOT)) {
        case 'jei': modRuntimeOnly("mezz.jei:jei-${minecraft_version}-forge:${jei_version}"); break
        case "disabled": break
        default: println("Unknown recipe viewer specified: $recipe_viewer. Must be JEI or disabled.")
    }

    implementation("io.github.llamalad7:mixinextras-forge:${mixin_extras_version}")
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))

    annotationProcessor "org.spongepowered:mixin:${mixin_version}:processor"

    /** Tests **/
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}

processResources {
    var replaceProperties = [
        minecraft_version_range: minecraft_version_range,
        forge_version_range: forge_version_range,
        loader_version_range: loader_version_range,
        mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
        mod_authors: mod_authors, mod_description: mod_description,
        create_version_range: create_version_range
    ]
    inputs.properties replaceProperties

    filesMatching(["META-INF/mods.toml"]) {
        expand(replaceProperties)
    }
}

jar {
    String name = base.archivesName.get()

    from("LICENSE") {
        rename { "${it}_${name}" }
    }

    manifest.attributes([
            "MixinConfigs": "createnuclear.forge.mixins.json",
            "Git-Hash"    : gitHash
    ])
}

tasks.named("sourcesJar") {
    manifest.attributes([
            "Git-Hash": gitHash
    ])
}

final slimJar = tasks.register("slimJar", Jar) {
    archiveClassifier = "slim"
    from(sourceSets.main.output)
    from(refmap)
    manifest.attributes([
        "MixinConfigs": "createnuclear.forge.mixins.json",
        "Git-Hash"    : gitHash
    ])
}
obfuscation.reobfuscate(slimJar, sourceSets.main)

project.publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId base.archivesName.get()
            from components.java

            artifact(tasks.reobfJar) {
                classifier = "all"
            }
        }
    }

    repositories {
        if (project.hasProperty("mavenUsername") && project.hasProperty("mavenPassword") && project.hasProperty("mavenURL")) {
            project.logger.lifecycle("Adding maven from secrets")

            maven {
                credentials {
                    username = project.property("mavenUsername") as String
                    password = project.property("mavenPassword") as String
                }
                url = URI.create(project.property("mavenURL") as String)
            }
        }

        if (project.hasProperty("mavendir")) {
            maven { url mavendir }
        }
    }
}

publishMods {
    file = reobfJar.archiveFile
    changelog = file("CHANGELOG.md").text
    type = STABLE
    version = "$mod_version"
    displayName = "$mod_name $mod_version for mc$minecraft_version"
    modLoaders.add("forge")
    // modLoaders.add("neoforge")

    // curseforge {
    //     accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
    //     projectId = ""
    //     minecraftVersions.add(minecraft_version)

    //     javaVersions.add(JavaVersion.VERSION_17)

    //     clientRequired = true
    //     serverRequired = true
    // }

    // modrinth {
    //     accessToken = providers.environmentVariable("MODRINTH_TOKEN")
    //     projectId = ""
    //     minecraftVersions.add(minecraft_version)

    //     requires {
    //         id = "LNytGWDc"
    //         slug = "Create"
    //     }
    //     optional {
    //         id = "u6dRKJwZ"
    //         slug = "JEI"
    //     }
    // }

    github {
        accessToken = providers.environmentVariable("GITHUB_TOKEN")
        repository = "Create-Nuclear-Team/CreateNuclearForge"
        commitish = gitHash
        tagName = "v${mod_version}-${gitHash.substring(0,7)}"

        allowEmptyFiles = true
    }
}

String calculateGitHash() {
    try {
        ExecOutput output = providers.exec {
            commandLine("git", "rev-parse", "HEAD")
        }
        return output.standardOutput.asText.get().trim()
    } catch (Throwable ignored) {
        return "unknown"
    }
}

boolean hasUnstaged() {
    try {
        ExecOutput output = providers.exec {
            commandLine("git", "status", "--porcelain")
        }
        String result = output.standardOutput.asText.get().replace("/M gradlew(\\.bat)?/", "").trim()
        if (!result.isEmpty())
            println("Found stageable results:\n ${result}\n")
        return !result.isEmpty()
    } catch (Throwable ignored) {
        return false
    }
}



